# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Tools.
# ------------------------------------------------------

TEMPLATE = app
TARGET = R6Tools
DESTDIR = ./x64/Release
CONFIG += release
LIBS += -L"."
DEPENDPATH += .
MOC_DIR += .
OBJECTS_DIR += release
UI_DIR += .
RCC_DIR += .
include(R6Tools.pri)

HEADERS += ./include/R6Tools.h
SOURCES += ./src/main.cpp \
    ./src/R6Tools.cpp
FORMS += ./R6Tools.ui
RESOURCES += R6Tools.qrc
